name: CI/CD Pipeline for IM Microservice

on:
  push:
    branches:
      - main               # Trigger the workflow on pushes to the main branch
    paths:
      - 'im_microservice/**'    # Trigger when changes occur in the im_microservice folder
  pull_request:
    branches:
      - main
    paths:
      - 'im_microservice/**'
  workflow_dispatch:            # Allows manual triggering from the Actions tab

jobs:
  build-and-deploy-im:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image for IM Microservice
        working-directory: ./im_microservice   # Set the working directory for the IM microservice
        run: docker build -t im-microservice:latest .

      - name: Deploy IM Microservice to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Securely accesses the Render API key from GitHub secrets
        run: |
          curl -fsSL https://cli.render.com/install | bash  # Installs Render CLI
          render services update Microservice_OfficialProject --branch main  # Deploys the service to Render
